#!/usr/bin/env php
<?php
/*
 * MIT License
 *
 * Copyright (c) 2021-2026 machinateur
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

declare(strict_types=1);

use App\Command\Schema2SrcCommand;
use App\NodeHandle;
use App\Service\DelegateDataService;
use App\Service\PdlDataService;
use App\Service\XsdDataService;
use Symfony\Component\Console\Application;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

// Define application/metadata constants.
include __DIR__ . '/meta.php';

if (false === \in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    echo PHP_EOL
        . sprintf('This application may only be invoked from a command line, got "%s".', PHP_SAPI)
        . PHP_EOL;

    exit(1);
}

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application(APP_NAME, APP_VERSION);
$dispatcher  = new EventDispatcher();

// TODO: Use factory instead to keep this file clean.
$twig = new Environment(new FilesystemLoader(__DIR__ . '/templates'), [
    // TODO: Use -vvv flag from input pre-parsing here.
    'debug'      => true,
    // Turn off auto-escape (regression to previous impl).
    'autoescape' => false,
    // TODO: Use cache to speed up operations, also for the model (new feature).
    'cache'      => false,
]);
$serviceXsd    = new XsdDataService($twig);
$servicePdl    = new PdlDataService($twig);
$serviceCompat = new DelegateDataService($serviceXsd, $servicePdl);

/** @var array<class-string<NodeHandle\NodeHandleInterface>> */
$nodeHandles = [
    NodeHandle\NodeHandleComplexContent::class,
    NodeHandle\NodeHandleSimpleContent::class,
    NodeHandle\NodeHandleComplexType::class,
    NodeHandle\NodeHandleIndicator::class,
    NodeHandle\NodeHandleElement::class,
    NodeHandle\NodeHandleSimpleType::class,
    NodeHandle\NodeHandleAttributeGroup::class,
    //NodeHandle\NodeHandleChain::class,
    NodeHandle\NodeHandleGroup::class,
    NodeHandle\NodeHandleExtension::class,
    NodeHandle\NodeHandleSchema::class,
    NodeHandle\NodeHandleRestriction::class,
    NodeHandle\NodeHandleAttribute::class,
];
foreach ($nodeHandles as $nodeHandle) {
    $serviceXsd->addNodeHandle(
            new $nodeHandle()
    );
}

$commands = [
    new Schema2SrcCommand($twig, $serviceCompat),
];

$application->setDispatcher($dispatcher);
$application->addCommands($commands);
$application->setDefaultCommand('schema2src', true);

$application->run();
