#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Command\Xsd2SrcCommand;
use App\NodeHandle;
use App\Service\DataService;
use Symfony\Component\Console\Application;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

// Define application/metadata constants.
include __DIR__ . '/meta.php';

if (false === \in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    echo PHP_EOL
        . sprintf('This application may only be invoked from a command line, got "%s".', PHP_SAPI)
        . PHP_EOL;

    exit(1);
}

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application(APP_NAME, APP_VERSION);
$dispatcher  = new EventDispatcher();

// TODO: Use factory instead to keep this file clean.
$twig = new Environment(new FilesystemLoader(__DIR__ . '/templates'), [
    // TODO: Use -vvv flag from input pre-parsing here.
    'debug'      => true,
    // Turn off auto-escape (regression to previous impl).
    'autoescape' => false,
    // TODO: Use cache to speed up operations, also for the model (new feature).
    'cache'      => false,
]);
$service = new DataService($twig);

/** @var array<class-string<NodeHandle\NodeHandleInterface>> */
$nodeHandles = [
    NodeHandle\NodeHandleComplexContent::class,
    NodeHandle\NodeHandleSimpleContent::class,
    NodeHandle\NodeHandleComplexType::class,
    NodeHandle\NodeHandleIndicator::class,
    NodeHandle\NodeHandleElement::class,
    NodeHandle\NodeHandleSimpleType::class,
    NodeHandle\NodeHandleAttributeGroup::class,
    //NodeHandle\NodeHandleChain::class,
    NodeHandle\NodeHandleGroup::class,
    NodeHandle\NodeHandleExtension::class,
    NodeHandle\NodeHandleSchema::class,
    NodeHandle\NodeHandleRestriction::class,
    NodeHandle\NodeHandleAttribute::class,
];
foreach ($nodeHandles as $nodeHandle) {
    $service->addNodeHandle(
            new $nodeHandle()
    );
}

$commands = [
    new Xsd2SrcCommand($twig, $service),
];

$application->setDispatcher($dispatcher);
$application->addCommands($commands);
$application->setDefaultCommand('xsd2src', true);

$application->run();
